spring:
  application:
    name: Challenge Team Hub Backend
  datasource:
    # Connects to localhost:5432 (your Docker container)
    url: jdbc:postgresql://${PGHOST:localhost}:${PGPORT:5432}/${PGDATABASE:ct_hub}
    username: ${PGUSER:dev}
    password: ${PGPASSWORD:dev}
    driver-class-name: org.postgresql.Driver
  jpa:
    # "update": Automatically creates/updates tables based on your Java code
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          batch_size: 50
        order_updates: true
        order_inserts: true
springdoc:
  writer-with-default-pretty-printer: true
  remove-broken-reference-definitions: false
management:
  endpoints:
    web:
      exposure:
        include: "health,metrics"